title: Roger Pou López # your name (or website title) here
logo: "/images/foto.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Physics Graduated currently seeking for a job
  <br><br>
  Strongly background in Data Science, Machine Learning and Deep learning
  <br><br>
  <a href="https://es.linkedin.com/in/roger-pou/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
